name: Deploy to Google Cloud Run

on:
    push:
        branches: [main]
    workflow_dispatch:

env:
    PROJECT_ID: personal-projects-468006
    SERVICE_NAME: personal-portfolio
    REGION: us-central1

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create environment file with secrets
              run: |
                  echo "VITE_EMAILJS_SERVICE_ID=${{ secrets.EMAILJS_SERVICE_ID }}" >> .env
                  echo "VITE_EMAILJS_TEMPLATE_ID=${{ secrets.EMAILJS_TEMPLATE_ID }}" >> .env
                  echo "VITE_EMAILJS_PUBLIC_KEY=${{ secrets.EMAILJS_PUBLIC_KEY }}" >> .env
                  cat .env

            - name: Create config.js file with secrets (backup approach)
              run: |
                  echo 'export const emailConfig = {
                    serviceId: "${{ secrets.EMAILJS_SERVICE_ID }}",
                    templateId: "${{ secrets.EMAILJS_TEMPLATE_ID }}",
                    publicKey: "${{ secrets.EMAILJS_PUBLIC_KEY }}"
                  };' > src/config.js

            # Authenticate to Google Cloud
            - id: "auth"
              name: "Authenticate to Google Cloud"
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GCP_SA_KEY }}"

            # Setup gcloud CLI
            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v1"

            # Enable required APIs
            - name: "Enable required APIs"
              run: |
                  gcloud services enable artifactregistry.googleapis.com
                  gcloud services enable run.googleapis.com
                  gcloud services enable cloudbuild.googleapis.com

            # Configure Docker to use gcloud credentials
            - name: "Configure Docker for GCR"
              run: gcloud auth configure-docker gcr.io --quiet

            - name: Build and push Docker image
              run: |
                  # Print auth info for debugging (no sensitive data printed)
                  gcloud auth list

                  # Build and push with proper tags
                  docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
                  docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

            - name: Deploy to Cloud Run
              run: |
                  # Set project for deployment
                  gcloud config set project ${{ env.PROJECT_ID }}

                  # Deploy to Cloud Run
                  gcloud run deploy ${{ env.SERVICE_NAME }} \
                    --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
                    --platform managed \
                    --region ${{ env.REGION }} \
                    --allow-unauthenticated

                  # Display the service URL
                  echo "🚀 Service deployed to:"
                  gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format="value(status.url)"
